### ISSUE TITLE
Variant catalog update hg38

### ISSUE THREAD

**Issue by cogrho** [Clinical-Genomics/stranger#50]
Hi!

I've noticed that after updating the demo variant catalog for hg38, many reference region coordinates and/or locus structures have changed. Interestingly, some of these coordinates also differ from those in the newest version of the original ExpansionHunter variant catalog. Some of the affected loci IDs include _ATN1, ATXN1, ATXN3, PHOX2B, TBP, FOXL2, HOXD13, RUNX2, ZIC2, ZIC3_. Is this intentional?

**Comment by dnil** [comment]
Thank you for the vigilance - we will check!

In general, I would advise to only use the demo files for demo purposes. For production, pick a set that sees actual use, say from here https://github.com/Clinical-Genomics/reference-files/tree/master/rare-disease/disease_loci/ExpansionHunter-v5.0.0. The definition files provided with this repo are not intended to replace dbs like https://harrietdashnow.com/STRchive/.

**Comment by dnil** [comment]
Ok, thank you again! I was afraid I had jumbled hg19 and hg38, but the changes listed appear to be about slight ambiguity on the first/last few repetitions. There is a mix of literature definitions and technical reasons for these. In general they are probably more leaning on due to us syncing up a bit with https://stripy.org/ for easy comparisons. The calls will look slightly different; what is best, I will leave to you of future reports to tell, but keep in mind that you may need to adjust your NormalMax and PathologicMin accordingly. 

I heartily encourage feedback and discussion on specific loci, but it would seem in general they are as intended, and have indeed been modified from the initial `ExpansionHunter` catalog values. Cheers!
